
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # kafdrop:
  #   image: obsidiandynamics/kafdrop:latest
  #   container_name: kafdrop
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     KAFKA_BROKERCONNECT: "kafka-broker:9092"
  #     JVM_OPTS: "-Xms32M -Xmx64M"

  # -----------------------
  # Auth Service
  # -----------------------
  shamba-auth:
    build:
      context: .
      dockerfile: apps/shamba_auth/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - apps/shamba_auth/.env
    depends_on:
      - kafka
      - zookeeper
      

  # -----------------------
  # API Gateway
  # -----------------------
  shamba-gateway:
    build:
      context: .
      dockerfile: apps/shamba_gateway/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - apps/shamba_gateway/.env
    depends_on:
      - shamba-auth
      - kafka
      - zookeeper


# -----------------------
#Volumes: Keep data persistent
# -----------------------
volumes:
  kafka_data:
  zookeeper_data: